services:
  web_server:
    container_name: pbr_web
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "3000:5000"
    depends_on:
      - postgres
  game_computer:
    container_name: pbr_game
    build:
      context: .
      dockerfile: docker/game.Dockerfile
    depends_on:
      - postgres
  postgres:
    container_name: pbr_psql
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
networks:
  pbr_network: {}
