services:

  web_server:
    container_name: pbr_web
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "3000:5000"
    depends_on:
      postgres:
        condition: service_healthy

  game_computer:
    container_name: pbr_game
    build:
      context: .
      dockerfile: docker/game.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: pbr_psql
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s

networks:
  pbr_network: {}
